"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.componentRouter = void 0;
var express_1 = require("express");
var componentDTO_1 = require("../../middlewares/DTOS/componentDTO");
var controller_1 = require("../../entities/component/controller");
var validation_1 = require("./validation");
var dto_1 = require("./dto");
var guard_1 = require("../../middlewares/guard");
exports.componentRouter = (0, express_1.Router)();
var Controller = new controller_1.ComponentController();
var Validation = new validation_1.ComponentValidation();
exports.componentRouter.get("/", guard_1.MIDDLEWARES.guest, Controller.getAll);
exports.componentRouter.get("/:id", guard_1.MIDDLEWARES.guest, Validation.get(), Controller.getOne);
exports.componentRouter.post("/", guard_1.MIDDLEWARES.user, Validation.create(), (0, componentDTO_1.componentDTO)(dto_1.CreateComponentDTO), Controller.create);
exports.componentRouter.patch("/", guard_1.MIDDLEWARES.user, Validation.update(), (0, componentDTO_1.componentDTO)(dto_1.UpdateComponentDTO), Controller.update);
exports.componentRouter.delete("/:id", guard_1.MIDDLEWARES.user, Validation.delete(), Controller.delete);
